Repository TeamPINGLE/PINGLE-ANDROID, pull requests merged in 2024-01, with the labels that each got.

#5 [init] 폰트 기초세팅
  app/build.gradle.kts
  app/src/main/res/font/suit_bold.otf
  app/src/main/res/font/suit_extrabold.otf
  app/src/main/res/font/suit_medium.otf
  app/src/main/res/font/suit_semibold.otf
  app/src/main/res/values/text_appearance.xml
Labels: ⚡️ init ⚡️, 🎅 민우 🎅

#8 [init] colors 기초 세팅
  app/src/main/res/values/colors.xml
Labels: ⚡️ init ⚡️, 🐹 지은 🐹

#11 [feat] category type 구현
  app/src/main/java/org/sopt/pingle/presentation/type/CategoryType.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐰 다은 🐰

#12 [init] 추가적인 기초 세팅 진행
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/util/base/BaseResponse.kt
  app/src/main/java/org/sopt/pingle/util/base/NullableBaseResponse.kt
  app/src/main/java/org/sopt/pingle/util/intent/IntentExt.kt
  app/src/main/res/drawable/ic_all_arrow_down_24.xml
  app/src/main/res/drawable/ic_all_arrow_left_24.xml
  app/src/main/res/drawable/ic_all_arrow_right_24.xml
  app/src/main/res/drawable/ic_all_arrow_up_24.xml
  app/src/main/res/drawable/ic_all_calendar_24.xml
  app/src/main/res/drawable/ic_all_check_default_24.xml
  app/src/main/res/drawable/ic_all_check_selected_24.xml
  app/src/main/res/drawable/ic_all_info_14.xml
  app/src/main/res/drawable/ic_all_map_24.xml
  app/src/main/res/drawable/ic_all_search_24.xml
  app/src/main/res/drawable/ic_all_user_24.xml
  app/src/main/res/drawable/ic_all_warning_notice_24.xml
  app/src/main/res/drawable/ic_all_x_24.xml
  app/src/main/res/drawable/ic_map_here_24.xml
  app/src/main/res/drawable/ic_map_list_24.xml
  app/src/main/res/drawable/ic_map_map_24.xml
  app/src/main/res/drawable/ic_navi_add_activate_24.xml
  app/src/main/res/drawable/ic_navi_add_inactivated_24.xml
  app/src/main/res/drawable/ic_navi_commend_active_24.xml
  app/src/main/res/drawable/ic_navi_commend_inactivated_24.xml
  app/src/main/res/drawable/ic_navi_home_active_24.xml
  app/src/main/res/drawable/ic_navi_home_inactivated_24.xml
  app/src/main/res/drawable/ic_navi_mypingle_active_24.xml
  app/src/main/res/drawable/ic_navi_mypingle_inactivated_24.xml
  app/src/main/res/drawable/ic_navi_setting_active_24.xml
  app/src/main/res/drawable/ic_navi_setting_inactivated_24.xml
  app/src/main/res/drawable/shape_border_radius_10.xml
  app/src/main/res/drawable/shape_border_radius_12.xml
  app/src/main/res/drawable/shape_border_radius_15.xml
  app/src/main/res/drawable/shape_border_radius_5.xml
  app/src/main/res/drawable/shape_border_radius_8.xml
  app/src/main/res/layout/view_all_topbar_arrow_with_title.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ⚡️ init ⚡️, 🐸 지현 🐸

#20 [feat] 커스텀 에딧 텍스트 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/dummy/DummyCustomDEditTextActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/res/drawable/cursor_drawble.xml
  app/src/main/res/layout/activity_edit_text_custom_test.xml
  app/src/main/res/layout/edit_text_pingle.xml
  app/src/main/res/values/attrs.xml
Labels: ✨ feat ✨, 🐰 다은 🐰

#18 [feat] Bottom Navigation + Status Bar
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/commend/CommendFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/setting/SettingFragment.kt
  app/src/main/res/drawable/ic_all_navi_add_active_24.xml
  app/src/main/res/drawable/ic_all_navi_add_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_commend_active_24.xml
  app/src/main/res/drawable/ic_all_navi_commend_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_home_active_24.xml
  app/src/main/res/drawable/ic_all_navi_home_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_mypingle_active_24.xml
  app/src/main/res/drawable/ic_all_navi_mypingle_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_setting_active_24.xml
  app/src/main/res/drawable/ic_all_navi_setting_inactivated_24.xml
  app/src/main/res/drawable/selector_all_navi_add.xml
  app/src/main/res/drawable/selector_all_navi_color.xml
  app/src/main/res/drawable/selector_all_navi_commend.xml
  app/src/main/res/drawable/selector_all_navi_home.xml
  app/src/main/res/drawable/selector_all_navi_mypingle.xml
  app/src/main/res/drawable/selector_all_navi_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_plan.xml
  app/src/main/res/layout/fragment_commend.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_my_pingle.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/menu/all_navi_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#24 [feat] chip + badge
  app/src/main/java/org/sopt/pingle/presentation/type/CategoryType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/dummy/DummyActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleBadge.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleChip.kt
  app/src/main/res/drawable/shape_border_radius_30.xml
  app/src/main/res/layout/badge_pingle.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#17 [feat] OnBording 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/type/GroupType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingAdapter.kt
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/view_on_boarding_group.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#23 [feat] 단체입장완료 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSuccessActivity.kt
  app/src/main/res/layout/activity_join_group_success.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#28 [feat] 메인 지도뷰 디폴트 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/PingleApp.kt
  app/src/main/java/org/sopt/pingle/domain/model/PinEntity.kt
  app/src/main/java/org/sopt/pingle/presentation/mapper/PinMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleChip.kt
  app/src/main/res/drawable/ic_map_location_overlay.xml
  app/src/main/res/drawable/ic_map_marker_multi_small.xml
  app/src/main/res/drawable/ic_map_marker_other_small.xml
  app/src/main/res/drawable/ic_map_marker_play_small.xml
  app/src/main/res/drawable/ic_map_marker_study_small.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ feat ✨, 🐸 지현 🐸

#30 [feat] 메인 지도 뷰 참여모달 구현
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapModalDialogFragment.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingDialogFragment.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleBadge.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleChip.kt
  app/src/main/java/org/sopt/pingle/util/view/ViewExt.kt
  app/src/main/res/layout/dialog_map_modal.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#32 [feat] Modal(Dialog) 재사용뷰 구현
  app/src/main/java/org/sopt/pingle/presentation/ui/common/AllModalDialogFragment.kt
  app/src/main/res/layout/dialog_all_modal.xml
  app/src/main/res/values/dimens.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#34 [feat] WebViewActivity 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/common/WebViewActivity.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
  app/src/main/java/org/sopt/pingle/util/fragment/FragmentExt.kt
  app/src/main/res/layout/activity_web_view.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#35 [feat] 기존단체입장(초대코드) view 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseJoinGroupCodeDto.kt
  app/src/main/java/org/sopt/pingle/domain/model/JoinGroupCodeEntity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/CustomSnackbar.kt
  app/src/main/java/org/sopt/pingle/util/view/ViewExt.kt
  app/src/main/res/color/selector_all_btn_background.xml
  app/src/main/res/color/selector_all_btn_text_color.xml
  app/src/main/res/drawable/shape_border_radius_50.xml
  app/src/main/res/layout/activity_join_group_code.xml
  app/src/main/res/layout/view_all_topbar_arrow_with_title.xml
  app/src/main/res/layout/view_snackbar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#43 [feat] 번개 생성 개최 뷰 - 시간 / 날짜 뷰 구현
  app/src/main/java/org/sopt/pingle/presentation/type/MeridiemType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanDateDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanDateTimeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanTimeDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/layout/dialog_time_picker.xml
  app/src/main/res/layout/edit_text_pingle.xml
  app/src/main/res/layout/fragment_plan_date_time.xml
  app/src/main/res/layout/view_text_with_title.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🐰 다은 🐰

#46 [docs] update README.md
  README.md
  app/src/main/java/org/sopt/pingle/presentation/type/MeridiemType.kt
Labels: 📕 docs 📕, 🐸 지현 🐸

#48 [mod] 커스텀 에딧 텍스트가 양방향 데이터 바인딩이 가능하도록 수정
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditTextReverseBinding.kt
  app/src/main/res/layout/edit_text_pingle.xml
  app/src/main/res/values/attrs.xml
Labels: 🌀 mod 🌀, 🐰 다은 🐰

#49 [feat] 번개 개최뷰 - 제목, 오픈채팅뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/type/PlanType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanOpenChattingFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanTitleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditTextReverseBinding.kt
  app/src/main/res/layout/activity_plan.xml
  app/src/main/res/layout/fragment_plan_open_chatting.xml
  app/src/main/res/layout/fragment_plan_title.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐰 다은 🐰, 😵‍💫 Code Review wanted 😵‍💫

#40 [feat] 메인 지도 뷰 카드 구현
  app/src/main/java/org/sopt/pingle/domain/model/PingleEntity.kt
  app/src/main/java/org/sopt/pingle/presentation/type/CategoryType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/common/AllModalDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapModalDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/res/color/selector_pingle_btn_m.xml
  app/src/main/res/color/selector_pingle_btn_s.xml
  app/src/main/res/drawable/shape_oval_stroke_1.xml
  app/src/main/res/layout/card_pingle.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🐸 지현 🐸, 😵‍💫 Code Review wanted 😵‍💫

#37 [feat] 핑글 개최 프로세스 - 장소 선택 뷰 구현
  .idea/misc.xml
  app/src/main/java/org/sopt/pingle/domain/model/PlanEntity.kt
  app/src/main/java/org/sopt/pingle/domain/model/PlanLocationEntity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationDiffCallback.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationDivider.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationViewModel.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingAdapter.kt
  app/src/main/res/layout/fragment_plan_location.xml
  app/src/main/res/layout/item_plan_location.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹

#56 [feat] 핑글 개최 프로세스 - 카테고리 선택 뷰 구현
  app/src/main/java/org/sopt/pingle/presentation/type/CategoryType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanCategoryFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingAdapter.kt
  app/src/main/res/drawable/background_disabled_plan_location_category.xml
  app/src/main/res/drawable/background_enabled_plan_location_category.xml
  app/src/main/res/drawable/selector_item_plan_location_category.xml
  app/src/main/res/layout/fragment_plan_category.xml
  app/src/main/res/layout/view_plan_category_type.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#62 [mod] 핑글 개최 프로세스 - 카테고리 선택 뷰 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanCategoryFragment.kt
Labels: 🌀 mod 🌀, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#64 [mod] 핑글 개최 프로세스 - 장소 선택 뷰 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationFragment.kt
  app/src/main/res/layout/fragment_plan_location.xml
  app/src/main/res/layout/item_plan_location.xml
Labels: 🌀 mod 🌀, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#57 [feat] 메인 지도 뷰 전체적인 연결
  app/src/main/java/org/sopt/pingle/presentation/mapper/CategoryTypeMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/mapper/PinMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/model/MarkerModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/res/drawable/ic_map_marker_multi_big.xml
  app/src/main/res/drawable/ic_map_marker_other_big.xml
  app/src/main/res/drawable/ic_map_marker_play_big.xml
  app/src/main/res/drawable/ic_map_marker_study_big.xml
Labels: ✨ feat ✨, 🐸 지현 🐸, 😵‍💫 Code Review wanted 😵‍💫

#53 [mod] 번개 개최 뷰 - 날짜/시간 부분 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanDateTimeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanTimeDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/util/CombineAll.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐰 다은 🐰, 😵‍💫 Code Review wanted 😵‍💫

#55 [feat] 번개 개최뷰 나가기 모달, 프로그래스바 구현
  app/build.gradle.kts
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/AllModalDialogFragment.kt
  app/src/main/res/layout/activity_plan.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ feat ✨, 🐰 다은 🐰

#60 [feat] 핑글 개최 프로세스 - 모집인원 입력 뷰 구현
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanRecruitmentFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/res/color/selector_plan_recruitment_btn.xml
  app/src/main/res/color/selector_plan_recruitment_btn_text.xml
  app/src/main/res/layout/fragment_plan_recruitment.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#70 [mod] editText 입력시 버튼 활성화 구현
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/res/layout/activity_join_group_code.xml
Labels: 🌀 mod 🌀, 🎅 민우 🎅

#68 [feat] 핑글 개최 프로세스 - 핑글 개최 안내 페이지 뷰 구현
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanAnnouncementActivity.kt
  app/src/main/res/drawable-xhdpi/ic_plan_announcement_graphic.png
  app/src/main/res/drawable-xxhdpi/ic_plan_announcement_graphic.png
  app/src/main/res/drawable/ic_plan_announcement_graphic.png
  app/src/main/res/layout/activity_plan_announcement.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#65 [feat] 핑글 개최 프로세스 - 내용요약/확인 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanCategoryFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanSummaryConfirmationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationFragment.kt
  app/src/main/res/layout/fragment_plan_summary_confirmation.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
Labels: ✨ feat ✨, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#52 [feat] 회원가입(로그인) 뷰 구현
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/PingleApp.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/res/drawable/ic_kakao_24.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ feat ✨, 🎅 민우 🎅

#67 [faet] 단체 입장 검색 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseJoinGroupSearchDto.kt
  app/src/main/java/org/sopt/pingle/domain/model/JoinGroupSearchEntity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/res/layout/activity_join_group_search.xml
  app/src/main/res/layout/item_join_group_search.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🎅 민우 🎅, 😵‍💫 Code Review wanted 😵‍💫

#72 [fix] 장소 선택 뷰 단일선택 로직 버그 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationViewModel.kt
Labels: 🛠️ fix 🛠️, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#80 [feat] 라이팅 수정(다은)
  app/src/main/res/layout/fragment_plan_open_chatting.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐰 다은 🐰

#82 [feat] 개최 프로세스 에셋 추가/라이팅 수정
  app/src/main/java/org/sopt/pingle/presentation/type/CategoryType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanRecruitmentFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/res/drawable-xhdpi/img_plan_announcement_graphic.png
  app/src/main/res/drawable-xhdpi/img_plan_cat_multi_1000_3.png
  app/src/main/res/drawable-xhdpi/img_plan_cat_others_1000_1.png
  app/src/main/res/drawable-xhdpi/img_plan_cat_play_1000_4.png
  app/src/main/res/drawable-xhdpi/img_plan_cat_study_1000_6.png
  app/src/main/res/drawable-xxhdpi/img_plan_announcement_graphic.png
  app/src/main/res/drawable-xxhdpi/img_plan_cat_multi_1000_3.png
  app/src/main/res/drawable-xxhdpi/img_plan_cat_others_1000_1.png
  app/src/main/res/drawable-xxhdpi/img_plan_cat_play_1000_4.png
  app/src/main/res/drawable-xxhdpi/img_plan_cat_study_1000_6.png
  app/src/main/res/drawable/img_plan_announcement_graphic.png
  app/src/main/res/drawable/img_plan_cat_multi_1000_3.png
  app/src/main/res/drawable/img_plan_cat_others_1000_1.png
  app/src/main/res/drawable/img_plan_cat_play_1000_4.png
  app/src/main/res/drawable/img_plan_cat_study_1000_6.png
  app/src/main/res/layout/activity_plan_announcement.xml
  app/src/main/res/layout/fragment_plan_recruitment.xml
  app/src/main/res/layout/view_plan_category_type.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹

#76 [feat] 더보기 뷰 구현
  app/src/main/java/org/sopt/pingle/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/setting/SettingFragment.kt
  app/src/main/res/layout/activity_plan_announcement.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐰 다은 🐰, 😵‍💫 Code Review wanted 😵‍💫

#85 [mod] 소셜로그인~지도까지 view 연결
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSuccessActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/OnBoardingActivity.kt
  app/src/main/res/layout/activity_join_group_search.xml
Labels: 🌀 mod 🌀, 🎅 민우 🎅

#84 [feat] 개최 프로세스 버튼 활성화 및 뷰 연결
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanAnnouncementActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
Labels: ✨ feat ✨, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#88 [feat] 에셋 추가 및 수정사항 반영 - 민우
  app/src/main/java/org/sopt/pingle/presentation/type/GroupType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/res/drawable-xhdpi/img_app_logo.png
  app/src/main/res/drawable-xhdpi/img_create_graphic.png
  app/src/main/res/drawable-xhdpi/img_join_group_success_graphic.png
  app/src/main/res/drawable-xhdpi/img_search_graphic.png
  app/src/main/res/drawable-xxhdpi/img_app_logo.png
  app/src/main/res/drawable-xxhdpi/img_create_graphic.png
  app/src/main/res/drawable-xxhdpi/img_join_group_success_graphic.png
  app/src/main/res/drawable-xxhdpi/img_search_graphic.png
  app/src/main/res/drawable/img_app_logo.png
  app/src/main/res/drawable/img_create_graphic.png
  app/src/main/res/drawable/img_join_group_success_graphic.png
  app/src/main/res/drawable/img_search_graphic.png
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_join_group_code.xml
  app/src/main/res/layout/activity_join_group_search.xml
  app/src/main/res/layout/activity_join_group_success.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/view_all_topbar_arrow_with_title.xml
  app/src/main/res/layout/view_on_boarding_group.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🎅 민우 🎅, 😵‍💫 Code Review wanted 😵‍💫

#91 [chore] 전체적인 뷰 연결 및 각종 이슈 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/type/CategoryType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSuccessActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planannouncement/PlanAnnouncementActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plancategory/PlanCategoryFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plandatetime/PlanDateDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plandatetime/PlanDateTimeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plandatetime/PlanTimeDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planopenchatting/PlanOpenChattingFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planrecruitment/PlanRecruitmentFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plansummaryconfirmation/PlanSummaryConfirmationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plantitle/PlanTitleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleSnackbar.kt
  app/src/main/res/drawable/background_disabled_plan_location_category.xml
  app/src/main/res/drawable/ic_all_navi_add_active_24.xml
  app/src/main/res/drawable/ic_all_navi_add_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_commend_active_24.xml
  app/src/main/res/drawable/ic_all_navi_commend_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_more_active_24.xml
  app/src/main/res/drawable/ic_all_navi_more_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_mypingle_active_24.xml
  app/src/main/res/drawable/ic_all_navi_mypingle_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_plan_active_24.xml
  app/src/main/res/drawable/ic_all_navi_plan_inactivated_24.xml
  app/src/main/res/drawable/ic_all_navi_setting_active_24.xml
  app/src/main/res/drawable/ic_all_navi_setting_inactivated_24.xml
  app/src/main/res/drawable/selector_all_navi_add.xml
  app/src/main/res/drawable/selector_all_navi_more.xml
  app/src/main/res/drawable/selector_all_navi_plan.xml
  app/src/main/res/drawable/selector_all_navi_setting.xml
  app/src/main/res/drawable/selector_item_plan_location_category.xml
  app/src/main/res/drawable/selector_plan_category_type_background.xml
  app/src/main/res/drawable/shape_line_white_radius_10.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_plan_announcement.xml
  app/src/main/res/layout/fragment_more.xml
  app/src/main/res/layout/fragment_plan_category.xml
  app/src/main/res/layout/fragment_plan_location.xml
  app/src/main/res/layout/fragment_plan_recruitment.xml
  app/src/main/res/layout/view_on_boarding_group.xml
  app/src/main/res/layout/view_plan_category_type.xml
  app/src/main/res/menu/all_navi_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ➰ chore ➰, 🐸 지현 🐸, 😵‍💫 Code Review wanted 😵‍💫

#93 [feat] 안드로이드 12 스플래시 버전 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-xhdpi/img_splash_logo.png
  app/src/main/res/drawable-xxhdpi/img_splash_logo.png
  app/src/main/res/drawable/img_splash_logo.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: ✨ feat ✨, 🐸 지현 🐸, 😵‍💫 Code Review wanted 😵‍💫

#100 [chore] Topbar 백버튼, 나가기 터치영역 변경
  app/src/main/res/layout/activity_plan_announcement.xml
  app/src/main/res/layout/view_all_topbar_arrow_with_title.xml
Labels: ➰ chore ➰, 🎅 민우 🎅

#101 [feat] 핀 클릭 시 번개 목록 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/datasource/remote/MapRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/MapRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponsePingleListDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/MapRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/MapService.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/MapRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetPingleListUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/mapper/PinMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#97 [faet] 카카오 소셜로그인 api 통신
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/datasource/local/PingleLocalDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasource/remote/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/request/RequestAuthDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseAuthDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/AuthService.kt
  app/src/main/java/org/sopt/pingle/data/service/KakaoAuthService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/KakaoModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/domain/model/AuthEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/splash/SplashActivity.kt
Labels: ✨ feat ✨, 🎅 민우 🎅

#105 [feat] 번개 참여 및 취소하기 API 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/datasource/remote/PingleRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/PingleRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/MapRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/PingleRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/PingleService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/PingleRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/PostPingleCancelUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/PostPingleJoinUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/res/layout/card_pingle.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#106 [feat] 장소 검색 API 연동
  app/src/main/java/org/sopt/pingle/data/datasource/remote/PlanRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/PlanRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/request/RequestPlanDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponsePlanDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/PlanRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/PlanService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/PlanRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetPlanLocationListUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/model/PlanLocationModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plancategory/PlanCategoryFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plandatetime/PlanDateTimeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planopenchatting/PlanOpenChattingFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planrecruitment/PlanRecruitmentFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plansummaryconfirmation/PlanSummaryConfirmationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plantitle/PlanTitleFragment.kt
Labels: ✨ feat ✨, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#108 [faet] 기존단체입장 초대코드 api 통신
  app/src/main/java/org/sopt/pingle/data/datasource/local/PingleLocalDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasource/remote/JoinGroupRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/JoinGroupRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/mapper/RequestJoinGroupCodeEntityMapper.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/request/RequestJoinGroupCodeDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseJoinGroupCodeDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseJoinGroupInfoDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/JoinGroupRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/JoinGroupService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/model/JoinGroupInfoEntity.kt
  app/src/main/java/org/sopt/pingle/domain/model/RequestJoinGroupCodeEntity.kt
  app/src/main/java/org/sopt/pingle/domain/model/ResponseJoinGroupCodeEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/JoinGroupRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetJoinGroupInfoUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/PostJoinGroupCodeUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/res/layout/activity_join_group_code.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#113 [mod] 메인 지도 뷰 관련 이슈 해결
  app/src/main/java/org/sopt/pingle/presentation/mapper/PinMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/mapper/PingleMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/res/layout/card_pingle.xml
Labels: 🌀 mod 🌀, 🐸 지현 🐸, 😵‍💫 Code Review wanted 😵‍💫

#114 [faet] 기존단체입장 단체검색 api 통신
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/datasource/remote/JoinGroupRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/JoinGroupRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseJoinGroupSearchDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/JoinGroupRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/JoinGroupService.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/JoinGroupRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetJoinGroupSearchUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/res/layout/activity_join_group_search.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#112 [feat] 더보기 뷰 - 유저정보 API 연동, 웹뷰 연결
  app/src/main/java/org/sopt/pingle/data/datasource/remote/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseUserInfoDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/AuthService.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/model/GroupEntity.kt
  app/src/main/java/org/sopt/pingle/domain/model/UserInfoEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetUserInfoUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/common/WebViewActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreViewModel.kt
Labels: ✨ feat ✨, 🐸 지현 🐸, 😵‍💫 Code Review wanted 😵‍💫

#116 [feat] 개최 프로세스 - 유저 정보 불러오기 API 연동
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/planlocation/PlanLocationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plansummaryconfirmation/PlanSummaryConfirmationFragment.kt
Labels: ✨ feat ✨, 🐸 지현 🐸

#120 [feat] 단체가 여러 개일 경우에 대한 처리
  app/src/main/java/org/sopt/pingle/presentation/mapper/PinMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/layout/item_join_group_search.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#127 [mod] 시간/날짜 뷰 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plandatetime/PlanDateDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/plan/plandatetime/PlanDateTimeFragment.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐰 다은 🐰

#122 [feat] 토큰 재발급 구현
  app/src/main/java/org/sopt/pingle/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseReissueDTO.kt
  app/src/main/res/layout/dialog_all_modal.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐰 다은 🐰

#126 [fix] 핀 클릭 시 번개 목록 API 수정
  app/src/main/java/org/sopt/pingle/data/datasource/remote/MapRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/MapRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponsePingleListDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/MapRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/MapService.kt
  app/src/main/java/org/sopt/pingle/domain/model/PingleEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/MapRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetPingleListUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
Labels: 🛠️ fix 🛠️, 🐸 지현 🐸

#129 [feat] 릴리즈 준비
  .github/workflows/pr_builder.yml
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingAdapter.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
  app/src/main/java/org/sopt/pingle/util/fragment/FragmentExt.kt
  app/src/main/java/org/sopt/pingle/util/intent/IntentExt.kt
  app/src/main/java/org/sopt/pingle/util/view/ViewExt.kt
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ feat ✨, 🐸 지현 🐸

#135 [fix] 1차 QA 수정사항 반영 - 지은
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planrecruitment/PlanRecruitmentFragment.kt
  app/src/main/res/layout/activity_plan_announcement.xml
  app/src/main/res/layout/fragment_plan_recruitment.xml
Labels: 🛠️ fix 🛠️, 🐹 지은 🐹

#137 [fix] 1차 QA 수정사항 반영 - 민우
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSuccessActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/splash/SplashActivity.kt
Labels: 🛠️ fix 🛠️, 🎅 민우 🎅

#139 [fix] 1차 QA 수정사항 반영 - 지현
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanActivity.kt
  app/src/main/res/drawable/ic_pin_multi_active.xml
  app/src/main/res/drawable/ic_pin_multi_default.xml
  app/src/main/res/drawable/ic_pin_play_active.xml
  app/src/main/res/drawable/ic_pin_play_default.xml
  app/src/main/res/drawable/ic_pin_study_active.xml
  app/src/main/res/drawable/ic_pin_study_default.xml
  app/src/main/res/layout/card_pingle.xml
  app/src/main/res/layout/fragment_map.xml
Labels: 🛠️ fix 🛠️, 🐸 지현 🐸

#134 [fix] 1차 QA 반영 -다은
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/res/layout/fragment_more.xml
  app/src/main/res/layout/fragment_plan_title.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: 🛠️ fix 🛠️, 🐰 다은 🐰

#143 [fix] 핑글 개최 프로세스 STEP1 - 이전 버튼 클릭 시 STEP0으로 이동
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanActivity.kt
Labels: 🛠️ fix 🛠️, 🐹 지은 🐹

#144 [feat] 메인 지도 뷰 - 카드 가로 스크롤 기능 추가
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapCardAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapCardViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_map_pingle_card.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#148 [fix] 기존단체입장 초대코드 maxLength 속성 추가
  app/src/main/res/layout/activity_join_group_code.xml
Labels: 🛠️ fix 🛠️, 🎅 민우 🎅

#151 [fix] 메인 지도 뷰 카드 올라간 채로 카테고리 변경했을 때 카드 안 내려가는 버그 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
Labels: 🛠️ fix 🛠️, 🐸 지현 🐸

#153 [fix] 단체 검색, 장소 검색 뷰 - 아무것도 입력하지 않은 경우 서버통신하지 않도록 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planlocation/PlanLocationFragment.kt
Labels: 🛠️ fix 🛠️, 🐹 지은 🐹

#155 [refactor] 지도 카드 뷰 로직 리팩토링
  app/src/main/java/org/sopt/pingle/data/datasource/remote/PingleRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/PingleRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/PingleRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/PingleService.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/PingleRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/DeletePingleCancelUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/mapper/PingleMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/plansummaryconfirmation/PlanSummaryConfirmationFragment.kt
  app/src/main/java/org/sopt/pingle/util/CombineAll.kt
  app/src/main/java/org/sopt/pingle/util/ExtensionUtils.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleSnackbar.kt
  app/src/main/java/org/sopt/pingle/util/view/ViewExt.kt
Labels: 🍥 refactor 🍥, 🐸 지현 🐸

#156 [feat] 초대 코드 뷰 - 이미 가입한 단체에 대한 분기처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseReissueDto.kt
  app/src/main/java/org/sopt/pingle/presentation/type/SnackbarType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleSnackbar.kt
  app/src/main/res/drawable/ic_all_notice_24.xml
  app/src/main/res/layout/view_snackbar.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#158 [chore] 1.0.1 업데이트
  app/build.gradle.kts
Labels: ➰ chore ➰, 🐸 지현 🐸

#141 [feat] 메인 지도뷰/리스트뷰 - 참여현황 뷰 구현 및 API 연동
  app/src/main/java/org/sopt/pingle/data/datasource/remote/ParticipantRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/ParticipantRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseParticipantDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/ParticipantRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/ParticipantService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/model/ParticipantEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/ParticipantRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetParticipantListUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planlocation/PlanLocationFragment.kt
  app/src/main/res/layout/activity_participant.xml
  app/src/main/res/layout/item_participant.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹, 😵‍💫 Code Review wanted 😵‍💫

#161 [feat] 안드로이드 기본 이전 버튼 스택 관리
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanActivity.kt
Labels: ✨ feat ✨, 🐹 지은 🐹

#162 [fix] 자잘한 버그 수정 및 뷰 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSuccessActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantActivity.kt
  app/src/main/java/org/sopt/pingle/util/activity/Activity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleSnackbar.kt
  app/src/main/res/layout/activity_my_group.xml
  app/src/main/res/values/strings.xml
Labels: 🛠️ fix 🛠️, 🐸 지현 🐸

#163 [feat] 마이핑글 뷰 & 서버통신구현
  app/src/main/java/org/sopt/pingle/data/datasource/remote/PingleRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/PingleRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseMyPingleDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/JoinGroupRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/ParticipantRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/PingleRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/PingleService.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/model/MyPingleEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/JoinGroupRepository.kt
  app/src/main/java/org/sopt/pingle/domain/repository/ParticipantRepository.kt
  app/src/main/java/org/sopt/pingle/domain/repository/PingleRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/DeletePingleUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetJoinGroupInfoUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetJoinGroupSearchUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetMyPingleListUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetPingleListUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/PostJoinGroupCodeUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/type/MyPingleType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleAdatper.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/plandatetime/PlanDateTimeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/plansummaryconfirmation/PlanSummaryConfirmationFragment.kt
  app/src/main/java/org/sopt/pingle/util/ExtensionUtils.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/res/drawable/ic_my_chat_20.xml
  app/src/main/res/drawable/ic_my_edit_24.xml
  app/src/main/res/drawable/ic_my_trash_active_20.xml
  app/src/main/res/drawable/ic_my_trash_inactivated_20.xml
  app/src/main/res/drawable/img_my_56.xml
  app/src/main/res/drawable/shape_border_radius_8_stroke_1.xml
  app/src/main/res/layout/activity_join_group_search.xml
  app/src/main/res/layout/activity_join_group_success.xml
  app/src/main/res/layout/fragment_my_pingle.xml
  app/src/main/res/layout/item_my_pingle.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🎅 민우 🎅, 😵‍💫 Code Review wanted 😵‍💫

#167 [feat] 모임장 탈퇴 스낵바 구현
  app/src/main/java/org/sopt/pingle/data/service/KakaoAuthService.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#168 [feat] 마이핑글 - 팝업창 구현, 삭제하기 연결
  app/src/main/java/org/sopt/pingle/data/datasource/remote/PingleRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/PingleRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/PingleRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/PingleService.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/PingleRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/DeletePingleDeleteUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/type/MyPingleType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapCardAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapCardViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleAdatper.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantActivity.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingAdapter.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/java/org/sopt/pingle/util/view/ViewExt.kt
  app/src/main/res/layout/item_my_pingle.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#169 [fix] 2차 스프린트 QA 수정사항 반영
  app/src/main/java/org/sopt/pingle/data/model/remote/request/RequestPinListDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/request/RequestPlanDto.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
  app/src/main/res/drawable/shape_line_g_09_radius_8.xml
  app/src/main/res/drawable/shape_pingle_green_solid_width_1.xml
  app/src/main/res/layout/activity_join_group_search.xml
  app/src/main/res/layout/edit_text_pingle.xml
  app/src/main/res/layout/fragment_plan_location.xml
  app/src/main/res/layout/fragment_plan_recruitment.xml
  app/src/main/res/layout/item_my_pingle.xml
  app/src/main/res/layout/view_text_with_title.xml
Labels: 🛠️ fix 🛠️, 🐸 지현 🐸

#171 [chore] 1.1.0 업데이트
  app/build.gradle.kts
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapViewModel.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
Labels: ➰ chore ➰, 🐸 지현 🐸

#173 [docs] update README.md
  README.md
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: 📕 docs 📕, 🐸 지현 🐸
