Repository TeamPINGLE/PINGLE-ANDROID, pull requests merged in 2024-03, with the labels that each got.

#201 [feat] 나의 단체 뷰 구현
  app/src/main/java/org/sopt/pingle/data/datasource/local/PingleLocalDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseMyGroupDto.kt
  app/src/main/java/org/sopt/pingle/domain/model/MyGroupEntity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupModalDialogFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupOwnerViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupViewModel.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
  app/src/main/res/drawable/ic_my_group_menu_copy_20.xml
  app/src/main/res/drawable/ic_my_group_menu_share_20.xml
  app/src/main/res/drawable/ic_my_group_owner_58.xml
  app/src/main/res/drawable/ic_my_group_selected_owner_58.xml
  app/src/main/res/drawable/shape_border_radius_12_13.xml
  app/src/main/res/drawable/shape_line_white_radius_12.xml
  app/src/main/res/layout/activity_my_group.xml
  app/src/main/res/layout/dialog_my_group_modal.xml
  app/src/main/res/layout/item_my_group_default.xml
  app/src/main/res/layout/item_my_group_owner.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🐹 지은 🐹

#193 [feat] 온보딩 추가 설명 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/type/OnboardingExplanationType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboardingexplanation/OnboardingExplanationActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboardingexplanation/OnboardingExplanationAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboardingexplanation/OnboardingExplanationDescriptionViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboardingexplanation/OnboardingExplanationTitleViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboardingexplanation/OnboardingViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-xhdpi/img_onboarding_explanation_category.png
  app/src/main/res/drawable-xhdpi/img_onboarding_explanation_group.png
  app/src/main/res/drawable-xhdpi/img_onboarding_explanation_logo.png
  app/src/main/res/drawable-xhdpi/img_onboarding_explanation_pingle.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_explanation_category.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_explanation_group.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_explanation_logo.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_explanation_pingle.png
  app/src/main/res/drawable/img_onboarding_explanation_category.png
  app/src/main/res/drawable/img_onboarding_explanation_group.png
  app/src/main/res/drawable/img_onboarding_explanation_logo.png
  app/src/main/res/drawable/img_onboarding_explanation_pingle.png
  app/src/main/res/drawable/selector_indicator_onboarding.xml
  app/src/main/res/drawable/shape_indicator_onboarding_deselect_8.xml
  app/src/main/res/drawable/shape_indicator_onboarding_select_8.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_onboarding_explanation.xml
  app/src/main/res/layout/item_onboarding_explanation_description.xml
  app/src/main/res/layout/item_onboarding_explanation_title.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹

#199 [feat] 신규 단체 개설하기 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/NewGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/NewGroupViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupannouncement/NewGroupAnnouncementActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupcodeshare/NewGroupCodeShareActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupcreate/NewGroupCreateFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinfo/NewGroupInfoActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinput/NewGroupInputFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupkeyword/NewGroupKeywordFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/res/anim/slide_up.xml
  app/src/main/res/color/selector_pingle_tag_l_text_color.xml
  app/src/main/res/color/selector_plan_recruitment_btn_background.xml
  app/src/main/res/drawable-xhdpi/img_group_graphic.png
  app/src/main/res/drawable-xhdpi/img_info_impossible.png
  app/src/main/res/drawable-xhdpi/img_info_reissue.png
  app/src/main/res/drawable-xxhdpi/img_group_graphic.png
  app/src/main/res/drawable-xxhdpi/img_info_impossible.png
  app/src/main/res/drawable-xxhdpi/img_info_reissue.png
  app/src/main/res/drawable/ic_all_copy_24.xml
  app/src/main/res/drawable/ic_all_info_24.xml
  app/src/main/res/drawable/img_group_graphic.png
  app/src/main/res/drawable/img_info_impossible.png
  app/src/main/res/drawable/img_info_reissue.png
  app/src/main/res/layout/activity_new_group.xml
  app/src/main/res/layout/activity_new_group_announcement.xml
  app/src/main/res/layout/activity_new_group_code_share.xml
  app/src/main/res/layout/activity_new_group_info.xml
  app/src/main/res/layout/edit_text_pingle.xml
  app/src/main/res/layout/fragment_new_group_create.xml
  app/src/main/res/layout/fragment_new_group_input.xml
  app/src/main/res/layout/fragment_new_group_keyword.xml
  app/src/main/res/layout/view_all_topbar_arrow_with_title.xml
  app/src/main/res/layout/view_new_group_chip_keyword.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#203 [feat] 리스트 뷰 <-> 검색 뷰 <-> 지도 뷰 플로우 구현
  app/src/main/java/org/sopt/pingle/presentation/model/SearchModel.kt
  app/src/main/java/org/sopt/pingle/presentation/type/HomeViewType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planlocation/PlanLocationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/pingle/util/Intent/IntentExt.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleSearch.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_main_list.xml
  app/src/main/res/layout/search_pingle.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#207 [feat] 랭킹뷰 API 연동
  app/src/main/java/org/sopt/pingle/data/datasource/remote/RankingRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/RankingRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseRankingDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/RankingRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/RankingService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/RankingRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetRankingUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/ranking/RankingFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/ranking/RankingViewModel.kt
Labels: ✨ feat ✨, 🐸 지현 🐸

#212 [mod] 지도 뷰 API 수정사항 반영
  app/src/main/java/org/sopt/pingle/data/datasource/remote/MapRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/MapRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponsePinListDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/MapRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/MapService.kt
  app/src/main/java/org/sopt/pingle/domain/model/PinEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/MapRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetPinListWithoutFilteringUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/model/SearchModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/search/SearchActivity.kt
Labels: 🌀 mod 🌀, 🐸 지현 🐸

#219 [init] Amplitude 기초 세팅
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/PingleApp.kt
  app/src/main/java/org/sopt/pingle/util/AmplitudeUtils.kt
  gradle/libs.versions.toml
Labels: ⚡️ init ⚡️, 🐸 지현 🐸

#216 [feat] CustomSnackbar Check Type 추가
  app/src/main/java/org/sopt/pingle/presentation/type/SnackbarType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleSnackbar.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
  app/src/main/java/org/sopt/pingle/util/view/ViewExt.kt
  app/src/main/res/drawable/ic_all_check_24.xml
Labels: ✨ feat ✨, 🐹 지은 🐹

#214 [feat] 메인 리스트 뷰 API 연동 및 전체적인 플로우 점검
  app/src/main/java/org/sopt/pingle/data/datasource/remote/MainListRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasource/remote/MapRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/MainListRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/MapRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseMainListDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponsePinDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponsePingleDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/MainListRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/MapRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/MainListService.kt
  app/src/main/java/org/sopt/pingle/data/service/MapService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/MainListRepository.kt
  app/src/main/java/org/sopt/pingle/domain/repository/MapRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetMainListPingleListUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetMapPingleListUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/mapper/MainListPingleModelMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/mapper/PinMapper.kt
  app/src/main/java/org/sopt/pingle/presentation/model/MainListPingleModel.kt
  app/src/main/java/org/sopt/pingle/presentation/model/MarkerModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/ranking/RankingViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/search/SearchActivity.kt
  app/src/main/res/layout/fragment_main_list.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#221 [feat] Amplitude 개발 프로젝트 분리
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
Labels: ✨ feat ✨, 🐸 지현 🐸

#210 [feat] 나의 단체 뷰 API 연동
  app/src/main/java/org/sopt/pingle/data/datasource/local/PingleLocalDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasource/remote/MyGroupListRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/MyGroupListRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/repository/MyGroupListRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/MyGroupListService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/repository/MyGroupListRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetMyGroupListUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/type/OnboardingExplanationType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupViewModel.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
Labels: ✨ feat ✨, 🐹 지은 🐹

#204 [mod] 오픈채팅방 유효성검사
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planopenchatting/PlanOpenChattingFragment.kt
  app/src/main/res/values/strings.xml
Labels: 🌀 mod 🌀, 🎅 민우 🎅

#217 [feat] 신규단체개설 API 구현
  app/src/main/java/org/sopt/pingle/data/datasource/remote/NewGroupRemoteDataSource.kt
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/remote/NewGroupRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/request/RequestNewGroupCreateDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseNewGroupCheckNameDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseNewGroupCreateDto.kt
  app/src/main/java/org/sopt/pingle/data/model/remote/response/ResponseNewGroupKeywordsDto.kt
  app/src/main/java/org/sopt/pingle/data/repository/NewGroupRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/data/service/NewGroupService.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/domain/model/NewGroupCheckNameEntity.kt
  app/src/main/java/org/sopt/pingle/domain/model/NewGroupCreateEntity.kt
  app/src/main/java/org/sopt/pingle/domain/model/NewGroupKeywordEntity.kt
  app/src/main/java/org/sopt/pingle/domain/repository/NewGroupRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetNewGroupCheckNameUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/GetNewGroupKeywordsUserCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/PostNewGroupCreateUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/model/NewGroupModel.kt
  app/src/main/java/org/sopt/pingle/presentation/type/NewGroupType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/NewGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/NewGroupViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupannouncement/NewGroupAnnouncementActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupcodeshare/NewGroupCodeShareActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupcreate/NewGroupCreateFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinfo/NewGroupInfoActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinput/NewGroupInputFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupkeyword/NewGroupKeywordFragment.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/res/layout/activity_new_group.xml
  app/src/main/res/layout/activity_new_group_code_share.xml
  app/src/main/res/layout/edit_text_pingle.xml
  app/src/main/res/layout/fragment_new_group_create.xml
  app/src/main/res/layout/fragment_new_group_input.xml
  app/src/main/res/layout/fragment_new_group_keyword.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🎅 민우 🎅

#229 [feat] 핑글 카드 에러 분기처리 진행 (지도, 리스트, 마이핑글)
  app/src/main/java/org/sopt/pingle/data/repository/PingleRepositoryImpl.kt
  app/src/main/java/org/sopt/pingle/domain/repository/PingleRepository.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/DeletePingleCancelUseCase.kt
  app/src/main/java/org/sopt/pingle/domain/usecase/PostPingleJoinUseCase.kt
  app/src/main/java/org/sopt/pingle/presentation/model/MainListPingleModel.kt
  app/src/main/java/org/sopt/pingle/presentation/type/PingleCardErrorType.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleViewModel.kt
  app/src/main/java/org/sopt/pingle/util/view/UiState.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#231 [fix] SearchPingle에 텍스트 입력 시 focus가 사라지는 문제 해결
  app/src/main/java/org/sopt/pingle/util/component/PingleSearch.kt
Labels: 🛠️ fix 🛠️, 🐸 지현 🐸

#233 [feat] 온보딩 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSuccessActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/NewGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupannouncement/NewGroupAnnouncementActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupcodeshare/NewGroupCodeShareActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinput/NewGroupInputFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
Labels: ✨ feat ✨, 🎅 민우 🎅

#235 [feat] General 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/pingle/PingleApp.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
Labels: ✨ feat ✨, 🐸 지현 🐸

#238 [feat] 지도/리스트 뷰 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
Labels: ✨ feat ✨, 🐸 지현 🐸

#240 [feat] 랭킹 뷰 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/pingle/presentation/ui/main/ranking/RankingFragment.kt
Labels: ✨ feat ✨, 🐸 지현 🐸

#223 [mod] 나의 단체 뷰 수정사항 반영
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
  app/src/main/res/drawable/ic_my_group_owner_57.xml
  app/src/main/res/drawable/ic_my_group_owner_58.xml
  app/src/main/res/drawable/ic_my_group_selected_owner_58.xml
  app/src/main/res/drawable/shape_line_white_radius_12.xml
  app/src/main/res/layout/activity_my_group.xml
  app/src/main/res/layout/dialog_my_group_modal.xml
  app/src/main/res/layout/item_my_group_default.xml
  app/src/main/res/layout/item_my_group_owner.xml
  app/src/main/res/values/strings.xml
Labels: 🌀 mod 🌀, 🐹 지은 🐹

#225 [feat] 개최 프로세스 뷰 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/pingle/presentation/ui/main/planannouncement/PlanAnnouncementActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupcodeshare/NewGroupCodeShareActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/util/view/DateTimeUtils.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐹 지은 🐹

#227 [feat] 더보기 뷰(나의 단체 뷰) 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
Labels: ✨ feat ✨, 🐹 지은 🐹

#237 [feat] 마이핑글 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleViewHolder.kt
Labels: ✨ feat ✨, 🎅 민우 🎅

#247 [fix] 토큰 재발급 이슈 해결
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
Labels: 🛠️ fix 🛠️, 🐸 지현 🐸

#248 [fix] 3차 스프린트 QA 수정사항 반영
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSuccessActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/mygroup/MyGroupActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupannouncement/NewGroupAnnouncementActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/onboarding/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/pingle/util/ExtensionUtils.kt
  app/src/main/res/drawable/ic_my_group_owner_57.xml
  app/src/main/res/drawable/ic_my_group_selected_owner_58.xml
  app/src/main/res/layout/activity_onboarding_explanation.xml
  app/src/main/res/layout/fragment_more.xml
  app/src/main/res/layout/item_onboarding_explanation_description.xml
  app/src/main/res/layout/item_onboarding_explanation_title.xml
Labels: 🛠️ fix 🛠️, 🐹 지은 🐹

#249 [fix] 3차 스프린트 QA 수정사항 반영
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinput/NewGroupInputFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupkeyword/NewGroupKeywordFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_join_group_code.xml
  app/src/main/res/layout/activity_new_group_announcement.xml
  app/src/main/res/layout/item_join_group_search.xml
Labels: 🛠️ fix 🛠️, 🎅 민우 🎅

#250 [chore] 2.0.0 업데이트
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/data/datasourceimpl/local/PingleLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/pingle/di/DataSourceModule.kt
  app/src/main/java/org/sopt/pingle/di/RepositoryModule.kt
  app/src/main/java/org/sopt/pingle/di/ServiceModule.kt
  app/src/main/java/org/sopt/pingle/di/UseCaseModule.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupCodeActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/more/MoreFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planlocation/PlanLocationFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planopenchatting/PlanOpenChattingFragment.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingFragment.kt
  app/src/main/java/org/sopt/pingle/util/component/AllModalDialogFragment.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCardBottom.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleModalDialogFragment.kt
  app/src/main/java/org/sopt/pingle/util/view/ViewExt.kt
  app/src/main/res/drawable-xhdpi/img_work_graphic.png
  app/src/main/res/drawable-xxhdpi/img_work_graphic.png
  app/src/main/res/drawable/img_work_graphic.png
  app/src/main/res/drawable/selector_indicator_onboarding.xml
  app/src/main/res/drawable/shape_ring_g_03.xml
  app/src/main/res/drawable/shape_ring_white.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ➰ chore ➰, 🐸 지현 🐸

#252 [hotfix] 신규단체개설뷰 이슈 해결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/NewGroupViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinput/NewGroupInputFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupkeyword/NewGroupKeywordFragment.kt
  app/src/main/res/layout/activity_new_group_announcement.xml
Labels: 🐸 지현 🐸, 🔥 hotfix 🔥

#254 [hotfix] Snackbar로 인한 앱 터지는 현상
  app/src/main/java/org/sopt/pingle/presentation/ui/newgroup/newgroupinput/NewGroupInputFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/plandatetime/PlanDateTimeFragment.kt
Labels: 🛠️ fix 🛠️, 🎅 민우 🎅

#256 [chore] 2.0.1 업데이트
  app/build.gradle.kts
  app/src/main/res/layout/activity_join_group_code.xml
Labels: ➰ chore ➰, 🐸 지현 🐸
