Repository TeamPINGLE/PINGLE-ANDROID, pull requests merged in 2024-02, with the labels that each got.

#180 [feat] SearchBar 구현
  app/src/main/java/org/sopt/pingle/util/component/PingleEditText.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleSearch.kt
  app/src/main/res/drawable/ic_all_clear_18.xml
  app/src/main/res/layout/activity_join_group_code.xml
  app/src/main/res/layout/fragment_plan_open_chatting.xml
  app/src/main/res/layout/fragment_plan_title.xml
  app/src/main/res/layout/search_pingle.xml
  app/src/main/res/values/attrs.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#182 [fix] 메인 지도뷰/리스트뷰 - 참여현황 뷰 개최자 여러명인 버그 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantViewHolder.kt
Labels: 🛠️ fix 🛠️, 🐹 지은 🐹

#175 [mod] 다이얼로그 배경 색상 수정
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapModalDialogFragment.kt
  app/src/main/java/org/sopt/pingle/util/base/BindingDialogFragment.kt
  app/src/main/java/org/sopt/pingle/util/component/AllModalDialogFragment.kt
  app/src/main/res/layout/dialog_all_modal.xml
  app/src/main/res/layout/dialog_map_modal.xml
Labels: 🌀 mod 🌀, 🐸 지현 🐸

#192 [feat] 커스텀 Search Bar 적용
  app/src/main/java/org/sopt/pingle/presentation/ui/joingroup/JoinGroupSearchActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/planlocation/PlanLocationFragment.kt
  app/src/main/res/layout/activity_join_group_search.xml
  app/src/main/res/layout/fragment_plan_location.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#185 [refactor] 핑글 카드 커스텀 뷰 분리 및 지도 ViewPager Item 재구현
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapCardAdapter.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapCardViewHolder.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/mypingle/MyPingleFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/participant/ParticipantActivity.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCard.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCardBottom.kt
  app/src/main/java/org/sopt/pingle/util/component/PingleCardTop.kt
  app/src/main/res/layout/bottom_card_pingle.xml
  app/src/main/res/layout/card_pingle.xml
  app/src/main/res/layout/item_map_pingle_card.xml
  app/src/main/res/layout/top_card_pingle.xml
  app/src/main/res/values/strings.xml
Labels: 🍥 refactor 🍥, 🐸 지현 🐸

#187 [refactor] 리스트뷰 <-> 지도뷰 ViewPager로 리팩토링
  app/src/main/java/org/sopt/pingle/presentation/ui/main/MainActivity.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/HomeViewModel.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/mainlist/MainListFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/main/home/map/MapFragment.kt
  app/src/main/java/org/sopt/pingle/presentation/ui/plan/PlanActivity.kt
  app/src/main/java/org/sopt/pingle/util/view/PingleFragmentStateAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_main_list.xml
  app/src/main/res/layout/fragment_map.xml
Labels: 🍥 refactor 🍥, 🐸 지현 🐸

#188 [feat] 검색 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/pingle/presentation/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/pingle/util/context/ContextExt.kt
  app/src/main/res/drawable-xhdpi/img_search_pingle_graphic.png
  app/src/main/res/drawable-xxhdpi/img_search_pingle_graphic.png
  app/src/main/res/drawable/ic_my_my_56.xml
  app/src/main/res/drawable/img_search_pingle_graphic.png
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_my_pingle.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat ✨, 🐸 지현 🐸

#198 [feat] PingleTag 추가
  app/src/main/res/color/selector_pingle_tag_l_background.xml
  app/src/main/res/color/selector_pingle_tag_l_text_color.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat ✨, 🐹 지은 🐹
